//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : jogodedados
//  @ File Name : Dado.java
//  @ Date : 22/08/2016
//  @ Author : 
//
//




public class Dado {
	public int valorDaFace;
	public void lancar() {
            
            valorDaFace = 1 + (int)(Math.random() * 6);
            
            System.out.println("Face do dado após o lançamento: " + valorDaFace);
	}
}
